#!/bin/bash
# $@ must be a regular file(s)
# will not delete a file with a link count of 1, unless -f (force) is specified
if [[ $1 == -f ]] ; then force=y ; shift ; fi
for i in "$@" ; do
	if [[ -f "$i" ]] ; then
		if [[ -z $force ]] && (( $(stat -c "%h" "$i") == 1 )) ; then
			echo "not deleting $i (link count is 1)" >&2
		else
			rm -v "$i"
		fi
	fi
done
#EOF
