#!/bin/bash
# $1 must be a directory
if [[ -d "$1" ]] ; then
	# if there are no files or directories in $1 (empty dir) the directory is truly empty
	if isemptydir_with_ea "$1" && rmdir "$1" ; then
		exit 0
	else
		echo "$0: $1: directory not empty" >&2
		exit 1
	fi
else
	echo "$0: $1: not a directory" >&2
	exit 1
fi
#EOF
